
ali_source 'alibaba-specs' #集团内部仓库

ali_source 'alibaba-specs-mirror' #官方镜像仓库

platform :ios, '9.0'

target 'AlivcBasicVideo_Example' do
  pod 'AlivcBasicVideo', :path => '../'
  pod 'AlivcCommon', :path => '../../AlivcCommon/'
  
  pod 'MRDLNA',:git => 'https://github.com/MQL9011/MRDLNA.git'

end
